### ISSUE TITLE
Practice Figure Wrong in Visualization 2

### ISSUE THREAD

**Issue by SanD94** [psych252/psych252book#3]
Depending on what it's written in visualization 2 part, the [figure](https://github.com/psych252/psych252book/blob/b31628969caf0f10add46a21171d5f65bdc1d033/03-visualization2.Rmd#L262) seems unrelated and it is also shown in [Visualization 1](https://github.com/psych252/psych252book/blob/b31628969caf0f10add46a21171d5f65bdc1d033/02-visualization1.Rmd).

**Comment by tobiasgerstenberg** [comment]
Thanks for pointing this out! It's fixed now.
