### ISSUE TITLE
Section 3.10

### ISSUE THREAD

**Issue by romeopenheiro** [psych252/psych252book#4]
Section 3.10 is missing a part of the following sentence: Snippets are short pieces of code that

**Comment by tobiasgerstenberg** [comment]
great -- thanks a lot for pointing this out! i'm teaching the course at the moment again, and will update the whole book once the course is done (end of march). i'll make sure to fix the part that you've mentioned.

**Comment by romeopenheiro** [comment]
Oh that's great. I am using this teaching material rn to learn some advanced stats. If you'd like, I can report issues that I come across as I go through the material.

**Comment by tobiasgerstenberg** [comment]
that would be fantastic -- thanks a lot! and make sure to check the slides that go with the different chapters here: https://github.com/psych252/psych252slides
